Added failing for non-empty output from linter

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -14,4 +14,11 @@ jobs:
     - uses: actions/checkout@v4
 
     - name: Lint
-      run: find . \( -iname '*.hpp' -o -iname '*.cpp' \) | xargs clang-format -style=Microsoft --dry-run
+      run: ERROR=$(find . \( -iname '*.hpp' -o -iname '*.cpp' \) | xargs clang-format -style=Microsoft --dry-run)
+        if [ -n "$ERROR" ]; then
+          echo "Linting dryrun failed..."
+          exit 1
+        else
+          echo "Linting dryrun successful!"
+          exit 0
+        fi
